### ISSUE TITLE
Content licensing

### ISSUE THREAD

**Issue by pierreprinetti** [gophercloud/gophercloud.github.io#3]
"© 2023. All rights reserved." appears on several pages of the website. That is not acceptable for an open source project.

Is there a chance we can relicense, or is it better to just start everything from scratch?

Probably, given how outdated the whole content is, the best we can do as a first step is to replace everything with a link to https://pkg.go.dev/github.com/gophercloud/gophercloud

WDYT @EmilienM @mandre @till ?

**Comment by till** [comment]
Is the actual source of the website licensed? Sorry, haven't looked where it is. If it contains an acceptable license I would guess it's save to remove it.

The website generally seems like a lower barrier of entry. I think almost everything works with gophercloud once you update imports in the example code. So if possible, wouldn't mind saving it. 🙂

**Comment by pierreprinetti** [comment]
The [license file](https://github.com/gophercloud/gophercloud.github.io/blob/main/LICENSE.md) in the repo is a MIT license. My suspicion is that they didn't care about licensing, so they imported the theme's license and left whatever license claim came with the theme itself.

However, the intention here doesn't count much. The website clearly states "All rights reserved", and I wouldn't have imported it if I had noticed that earlier.

I am going to wipe the thing and start over.
